"""Tests for the error-info-disclosure hardening (issue #79).

The fix has three parts:

1. A request-id middleware that attaches (or reuses) an ``X-Request-ID``
   header on every response, including 500s generated by Starlette's
   outermost ``ServerErrorMiddleware``.
2. A global ``Exception`` handler that returns a sanitized 500 with
   the generic message + request id, never the raw exception text.
3. Replaced ``detail=str(e)`` callsites in
   ``orchestrator/main.py`` (chat completion) and the cookie policy
   paths in ``orchestrator/routes/auth_setup.py`` with stable error
   codes and server-side logging.
"""

from __future__ import annotations

import logging
import re
from pathlib import Path

import pytest
from fastapi import FastAPI
from httpx import ASGITransport, AsyncClient

from orchestrator.main import (
    REQUEST_ID_HEADER,
    _GENERIC_INTERNAL_ERROR,
    _generic_exception_handler,
    app,
)
from orchestrator.request_id import (
    REQUEST_ID_HEADER as REQUEST_ID_HEADER_CONST,
    RequestIdMiddleware,
    _OuterRequestIdMiddleware,
    _sanitize_inbound,
)


ROOT = Path(__file__).resolve().parents[1]


def _build_crash_app_with_handler() -> FastAPI:
    """Build a tiny FastAPI app with the production global exception handler
    and the outer request-id middleware wrap, so 500 responses generated
    by Starlette's outermost ServerErrorMiddleware carry both the
    sanitized body and the request id."""

    crash_app = FastAPI()
    crash_app.add_exception_handler(Exception, _generic_exception_handler)
    _built = crash_app.build_middleware_stack()
    crash_app.middleware_stack = _OuterRequestIdMiddleware(_built)
    return crash_app


# ---------------------------------------------------------------------------
# Sanitizer unit tests
# ---------------------------------------------------------------------------


def test_sanitize_inbound_passes_safe_values() -> None:
    assert _sanitize_inbound("req_abc123") == "req_abc123"
    assert _sanitize_inbound("a-b_c.d/e:f+g") == "a-b_c.d/e:f+g"


def test_sanitize_inbound_replaces_unsafe_chars() -> None:
    assert _sanitize_inbound("hello world\nfoo") == "hello_world_foo"
    assert _sanitize_inbound("<script>") == "_script_"


def test_sanitize_inbound_truncates_long_values() -> None:
    long = "a" * 5_000
    out = _sanitize_inbound(long)
    assert out is not None
    assert len(out) == 128


def test_sanitize_inbound_returns_none_for_empty() -> None:
    assert _sanitize_inbound("") is None
    # Whitespace is replaced with underscores (not dropped), so the
    # result is a non-empty string of underscores.
    assert _sanitize_inbound("   ") == "___"
    # Control characters are replaced with underscores, so the result
    # is a non-empty string of underscores (not None). The test for
    # "rejects CRLF injection" below verifies the security-relevant
    # property (no CR/LF surviving the cleaner).
    assert _sanitize_inbound("\x00\x01") == "__"


def test_sanitize_inbound_rejects_crlf_injection() -> None:
    """The sanitizer must not allow CRLF injection in the response header."""

    out = _sanitize_inbound("req_abc\r\nSet-Cookie: pwn=1")
    assert out is not None
    assert "\r" not in out
    assert "\n" not in out


# ---------------------------------------------------------------------------
# Request ID middleware
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_request_id_is_generated_when_no_header_provided() -> None:
    test_app = FastAPI()

    @test_app.get("/ok")
    async def ok() -> dict[str, str]:
        return {"status": "ok"}

    test_app.add_middleware(RequestIdMiddleware)

    async with AsyncClient(transport=ASGITransport(app=test_app), base_url="http://test") as client:
        response = await client.get("/ok")

    assert response.status_code == 200
    rid = response.headers[REQUEST_ID_HEADER_CONST]
    assert rid.startswith("req_")
    assert len(rid) > 8


@pytest.mark.asyncio
async def test_request_id_is_reused_when_inbound_header_valid() -> None:
    test_app = FastAPI()

    @test_app.get("/ok")
    async def ok() -> dict[str, str]:
        return {"status": "ok"}

    test_app.add_middleware(RequestIdMiddleware)

    async with AsyncClient(transport=ASGITransport(app=test_app), base_url="http://test") as client:
        response = await client.get("/ok", headers={REQUEST_ID_HEADER_CONST: "req_existing_123"})

    assert response.headers[REQUEST_ID_HEADER_CONST] == "req_existing_123"


@pytest.mark.asyncio
async def test_request_id_middleware_sanitizes_unsafe_inbound() -> None:
    test_app = FastAPI()

    @test_app.get("/ok")
    async def ok() -> dict[str, str]:
        return {"status": "ok"}

    test_app.add_middleware(RequestIdMiddleware)

    async with AsyncClient(transport=ASGITransport(app=test_app), base_url="http://test") as client:
        # CRLF injection attempt — the sanitizer must replace newlines and
        # the resulting id must not include them (http headers would
        # otherwise be split).
        response = await client.get(
            "/ok",
            headers={REQUEST_ID_HEADER_CONST: "evil\r\nSet-Cookie: pwn=1"},
        )

    rid = response.headers[REQUEST_ID_HEADER_CONST]
    assert "\r" not in rid
    assert "\n" not in rid
    # The middle should be replaced with underscores.
    assert "evil" in rid
    assert "Set-Cookie" in rid or "Set-Cookie: pwn=1" not in rid


@pytest.mark.asyncio
async def test_request_id_persisted_on_500_via_outer_wrap() -> None:
    """Unhandled exceptions are caught by Starlette's ``ServerErrorMiddleware``
    *outside* the user-added middleware. The outer wrap must still attach
    the request id to the 500 response."""

    crash_app = _build_crash_app_with_handler()

    @crash_app.get("/boom")
    async def boom() -> None:
        raise RuntimeError("intentional crash for request-id 500 regression test")

    async with AsyncClient(
        transport=ASGITransport(app=crash_app, raise_app_exceptions=False),
        base_url="http://test",
    ) as client:
        response = await client.get("/boom", headers={REQUEST_ID_HEADER_CONST: "req_crash_42"})

    assert response.status_code == 500
    assert response.headers[REQUEST_ID_HEADER_CONST] == "req_crash_42"


# ---------------------------------------------------------------------------
# Global exception handler — sanitized 500 response
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_unhandled_exception_returns_generic_message_no_leak() -> None:
    """Issue #79: unhandled exceptions must not leak Python exception text,
    file paths, or function names in the response body."""

    crash_app = _build_crash_app_with_handler()

    @crash_app.get("/boom")
    async def boom() -> None:
        # Use a very specific exception message that includes a recognizable
        # fingerprint so the assertion can detect any leak.
        raise RuntimeError("fingerprint-leak-7e3a9b: /orchestrator/secret_path.py leaked fn name")

    async with AsyncClient(
        transport=ASGITransport(app=crash_app, raise_app_exceptions=False),
        base_url="http://test",
    ) as client:
        response = await client.get("/boom")

    assert response.status_code == 500
    body = response.text
    assert "fingerprint-leak-7e3a9b" not in body
    assert "/secret_path.py" not in body
    assert "RuntimeError" not in body
    assert _GENERIC_INTERNAL_ERROR in body


@pytest.mark.asyncio
async def test_unhandled_exception_includes_request_id_in_body() -> None:
    """The request id is the correlation handle for support — it must be
    present in the response body for the operator fetch logs."""

    crash_app = _build_crash_app_with_handler()

    @crash_app.get("/boom")
    async def boom() -> None:
        raise RuntimeError("oh no")

    async with AsyncClient(
        transport=ASGITransport(app=crash_app, raise_app_exceptions=False),
        base_url="http://test",
    ) as client:
        response = await client.get("/boom", headers={REQUEST_ID_HEADER: "req_correlation_xyz"})

    assert response.status_code == 500
    body = response.json()
    assert body["request_id"] == "req_correlation_xyz"
    assert body["detail"] == _GENERIC_INTERNAL_ERROR


@pytest.mark.asyncio
async def test_unhandled_exception_logs_full_traceback(
    caplog: pytest.LogCaptureFixture,
) -> None:
    """The full traceback must be logged server-side for triage."""

    crash_app = _build_crash_app_with_handler()

    @crash_app.get("/boom")
    async def boom() -> None:
        raise RuntimeError("traceback-fingerprint-abc123")

    caplog.set_level(logging.ERROR, logger="orchestrator.main")

    async with AsyncClient(
        transport=ASGITransport(app=crash_app, raise_app_exceptions=False),
        base_url="http://test",
    ) as client:
        response = await client.get("/boom", headers={REQUEST_ID_HEADER: "req_log_42"})

    # The unique fingerprint must appear in the captured logs, with the
    # request id present for correlation.
    assert "traceback-fingerprint-abc123" in caplog.text
    assert "req_log_42" in caplog.text
    assert response.status_code == 500


# ---------------------------------------------------------------------------
# Real app regression — already-wired production app must also be sanitized
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_production_app_emits_request_id_header() -> None:
    """The real production app must register the request id on every
    response, including the OpenAPI schema endpoint used by SDK tooling."""

    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as client:
        response = await client.get("/openapi.json")

    assert response.status_code == 200
    rid = response.headers[REQUEST_ID_HEADER]
    assert rid.startswith("req_")


def test_production_app_supplies_stable_cookie_policy_error_code() -> None:
    """The auth_setup.py refresh endpoint must return a fixed error code
    instead of ``str(e)``. We can't easily trigger the actual cookie policy
    failure, so we visit the source and assert the literal token is
    present, and that the ``detail=str(e)`` pattern is gone."""

    auth_source = (ROOT / "orchestrator" / "routes" / "auth_setup.py").read_text()
    # The literal fix token must be present in both the setup and refresh
    # endpoints.
    assert auth_source.count("cookie_policy_invalid") >= 2
    # The leaky pattern must be gone from auth_setup.py.
    assert "detail=str(e)" not in auth_source


def test_production_app_omits_str_e_in_main_chat_completion() -> None:
    """The OpenAI-compatible chat completion endpoint must not leak
    ``str(e)`` in its 500 response."""

    main_source = (ROOT / "orchestrator" / "main.py").read_text()
    # The fix replaces the leaky `raise HTTPException(status_code=500,
    # detail=str(e))` pattern with `detail=_GENERIC_INTERNAL_ERROR`.
    # Check that the leaky pattern is gone (allowing other valid instances
    # elsewhere — but the specific chat-completion path is replaced).
    # We anchor on the chat completion route which is the one we changed.
    assert "OpenAI-compatible chat completion failed" in main_source


def test_main_py_no_new_detail_str_e_in_runtime_error_branches() -> None:
    """Static gate: the runtime-error path in ``/v1/chat/completions`` must
    not go back to leaking ``str(e)``. We accept the auth_setup path for
    the historical reason (well-scoped cookie policy errors are now a
    fixed token)."""

    main_source = (ROOT / "orchestrator" / "main.py").read_text()
    # The chat completion route's exception branch must use the generic
    # message constant, not ``str(e)``. The branch logging message is
    # the unique anchor — the comment block above only appears in this
    # route's exception handler.
    match = re.search(
        r"OpenAI-compatible chat completion failed.*?raise HTTPException\(\s*status_code=500,\s*detail=([^\n)]+)\)",
        main_source,
        flags=re.DOTALL,
    )
    assert match is not None, "Could not find the chat completion exception handler in main.py"
    detail_value = match.group(1).strip()
    assert detail_value == "_GENERIC_INTERNAL_ERROR", (
        f"Expected detail=_GENERIC_INTERNAL_ERROR, got {detail_value!r}"
    )
    assert "str(e)" not in match.group(0)
