"""Tests for the error-info-disclosure hardening (issue #79).

The fix has three parts:

1. A request-id middleware that attaches (or reuses) an ``X-Request-ID``
   header on every response, including 500s generated by Starlette's
   outermost ``ServerErrorMiddleware``.
2. A global ``Exception`` handler that returns a sanitized 500 with
   the generic message + request id, never the raw exception text.
3. Replaced ``detail=str(e)`` callsites in
   ``orchestrator/main.py`` (chat completion) and the cookie policy
   paths in ``orchestrator/routes/auth_setup.py`` with stable error
   codes and server-side logging.
"""

from __future__ import annotations

import logging
import re
from pathlib import Path

import pytest
from fastapi import FastAPI
from httpx import ASGITransport, AsyncClient

from orchestrator.main import (
    REQUEST_ID_HEADER,
    _GENERIC_INTERNAL_ERROR,
    _generic_exception_handler,
    app,
)
from orchestrator.request_id import (
    REQUEST_ID_HEADER as REQUEST_ID_HEADER_CONST,
    RequestIdMiddleware,
    _OuterRequestIdMiddleware,
    _sanitize_inbound,
)


ROOT = Path(__file__).resolve().parents[1]


def _build_crash_app_with_handler() -> FastAPI:
    """Build a tiny FastAPI app with the production global exception handler
    and the outer request-id middleware wrap, so 500 responses generated
    by Starlette's outermost ServerErrorMiddleware carry both the
    sanitized body and the request id."""

    crash_app = FastAPI()
    crash_app.add_exception_handler(Exception, _generic_exception_handler)
    _built = crash_app.build_middleware_stack()
    crash_app.middleware_stack = _OuterRequestIdMiddleware(_built)
    return crash_app


# ---------------------------------------------------------------------------
# Sanitizer unit tests
# ---------------------------------------------------------------------------


def test_sanitize_inbound_passes_safe_values() -> None:
    assert _sanitize_inbound("req_abc123") == "req_abc123"
    assert _sanitize_inbound("a-b_c.d/e:f+g") == "a-b_c.d/e:f+g"


def test_sanitize_inbound_replaces_unsafe_chars() -> None:
    assert _sanitize_inbound("hello world\nfoo") == "hello_world_foo"
    assert _sanitize_inbound("<script>") == "_script_"


def test_sanitize_inbound_truncates_long_values() -> None:
    long = "a" * 5_000
    out = _sanitize_inbound(long)
    assert out is not None
    assert len(out) == 128


def test_sanitize_inbound_returns_none_for_empty() -> None:
    assert _sanitize_inbound("") is None
    # Whitespace is replaced with underscores (not dropped), so the
    # result is a non-empty string of underscores.
    assert _sanitize_inbound("   ") == "___"
    # Control characters are replaced with underscores, so the result
    # is a non-empty string of underscores (not None). The test for
    # "rejects CRLF injection" below verifies the security-relevant
    # property (no CR/LF surviving the cleaner).
    assert _sanitize_inbound("\x00\x01") == "__"


def test_sanitize_inbound_rejects_crlf_injection() -> None:
    """The sanitizer must not allow CRLF injection in the response header."""

    out = _sanitize_inbound("req_abc\r\nSet-Cookie: pwn=1")
    assert out is not None
    assert "\r" not in out
    assert "\n" not in out


# ---------------------------------------------------------------------------
# Request ID middleware
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_request_id_is_generated_when_no_header_provided() -> None:
    test_app = FastAPI()

    @test_app.get("/ok")
    async def ok() -> dict[str, str]:
        return {"status": "ok"}

    test_app.add_middleware(RequestIdMiddleware)

    async with AsyncClient(transport=ASGITransport(app=test_app), base_url="http://test") as client:
        response = await client.get("/ok")

    assert response.status_code == 200
    rid = response.headers[REQUEST_ID_HEADER_CONST]
    assert rid.startswith("req_")
    assert len(rid) > 8


@pytest.mark.asyncio
async def test_request_id_is_always_server_generated_when_inbound_provided() -> None:
    """Round-1 fix: the inbound ``X-Request-ID`` is no longer reused as
    the correlation handle (the response ``X-Request-ID`` is always
    server-generated). The inbound value is preserved as
    ``X-Client-Request-ID`` so upstream proxies / load-test harnesses
    still have a handle.
    """

    test_app = FastAPI()

    @test_app.get("/ok")
    async def ok() -> dict[str, str]:
        return {"status": "ok"}

    test_app.add_middleware(RequestIdMiddleware)

    async with AsyncClient(transport=ASGITransport(app=test_app), base_url="http://test") as client:
        response = await client.get("/ok", headers={REQUEST_ID_HEADER_CONST: "req_existing_123"})

    # The correlation header is always server-generated.
    rid = response.headers[REQUEST_ID_HEADER_CONST]
    assert rid.startswith("req_")
    assert rid != "req_existing_123"
    # The inbound value is preserved as X-Client-Request-ID.
    assert response.headers.get("X-Client-Request-ID") == "req_existing_123"


@pytest.mark.asyncio
async def test_request_id_middleware_sanitizes_unsafe_inbound() -> None:
    test_app = FastAPI()

    @test_app.get("/ok")
    async def ok() -> dict[str, str]:
        return {"status": "ok"}

    test_app.add_middleware(RequestIdMiddleware)

    async with AsyncClient(transport=ASGITransport(app=test_app), base_url="http://test") as client:
        # CRLF injection attempt — the sanitizer must replace newlines and
        # the resulting id must not include them (http headers would
        # otherwise be split).
        response = await client.get(
            "/ok",
            headers={REQUEST_ID_HEADER_CONST: "evil\r\nSet-Cookie: pwn=1"},
        )

    # The correlation header is the sanitized inbound (when it survives
    # sanitization) under X-Client-Request-ID; X-Request-ID itself is
    # always a fresh server-generated id.
    rid = response.headers[REQUEST_ID_HEADER_CONST]
    assert rid.startswith("req_")
    # The inbound is sanitized — CRLF replaced with underscores.
    client_id = response.headers.get("X-Client-Request-ID", "")
    assert "\r" not in client_id
    assert "\n" not in client_id
    assert "evil" in client_id
    assert "Set-Cookie" in client_id or "Set-Cookie: pwn=1" not in client_id


@pytest.mark.asyncio
async def test_request_id_persisted_on_500_via_outer_wrap() -> None:
    """Unhandled exceptions are caught by Starlette's ``ServerErrorMiddleware``
    *outside* the user-added middleware. The outer wrap must still attach
    the request id to the 500 response.
    """

    crash_app = _build_crash_app_with_handler()

    @crash_app.get("/boom")
    async def boom() -> None:
        raise RuntimeError("intentional crash for request-id 500 regression test")

    async with AsyncClient(
        transport=ASGITransport(app=crash_app, raise_app_exceptions=False),
        base_url="http://test",
    ) as client:
        response = await client.get("/boom", headers={REQUEST_ID_HEADER_CONST: "req_crash_42"})

    assert response.status_code == 500
    # The 500 carries a server-generated X-Request-ID (round-1 fix: the
    # correlation id is always server-generated) and the inbound value
    # under X-Client-Request-ID.
    rid = response.headers[REQUEST_ID_HEADER_CONST]
    assert rid.startswith("req_")
    assert rid != "req_crash_42"
    assert response.headers.get("X-Client-Request-ID") == "req_crash_42"


# ---------------------------------------------------------------------------
# Global exception handler — sanitized 500 response
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_unhandled_exception_returns_generic_message_no_leak() -> None:
    """Issue #79: unhandled exceptions must not leak Python exception text,
    file paths, or function names in the response body."""

    crash_app = _build_crash_app_with_handler()

    @crash_app.get("/boom")
    async def boom() -> None:
        # Use a very specific exception message that includes a recognizable
        # fingerprint so the assertion can detect any leak.
        raise RuntimeError("fingerprint-leak-7e3a9b: /orchestrator/secret_path.py leaked fn name")

    async with AsyncClient(
        transport=ASGITransport(app=crash_app, raise_app_exceptions=False),
        base_url="http://test",
    ) as client:
        response = await client.get("/boom")

    assert response.status_code == 500
    body = response.text
    assert "fingerprint-leak-7e3a9b" not in body
    assert "/secret_path.py" not in body
    assert "RuntimeError" not in body
    assert _GENERIC_INTERNAL_ERROR in body


@pytest.mark.asyncio
async def test_unhandled_exception_includes_request_id_in_body() -> None:
    """The request id is the correlation handle for support — it must be
    present in the response body for the operator fetch logs."""

    crash_app = _build_crash_app_with_handler()

    @crash_app.get("/boom")
    async def boom() -> None:
        raise RuntimeError("oh no")

    async with AsyncClient(
        transport=ASGITransport(app=crash_app, raise_app_exceptions=False),
        base_url="http://test",
    ) as client:
        response = await client.get("/boom", headers={REQUEST_ID_HEADER: "req_correlation_xyz"})

    assert response.status_code == 500
    body = response.json()
    # The body carries the server-generated correlation id (round-1 fix:
    # the correlation handle is always server-generated to prevent an
    # attacker from pre-staging a known id to pollute log searches).
    assert body["request_id"].startswith("req_")
    assert body["request_id"] != "req_correlation_xyz"
    # The inbound value is preserved as the X-Client-Request-ID header.
    assert response.headers.get("X-Client-Request-ID") == "req_correlation_xyz"
    assert body["detail"] == _GENERIC_INTERNAL_ERROR


@pytest.mark.asyncio
async def test_unhandled_exception_logs_full_traceback(
    caplog: pytest.LogCaptureFixture,
) -> None:
    """The full traceback must be logged server-side for triage."""

    crash_app = _build_crash_app_with_handler()

    @crash_app.get("/boom")
    async def boom() -> None:
        raise RuntimeError("traceback-fingerprint-abc123")

    caplog.set_level(logging.ERROR, logger="orchestrator.main")

    async with AsyncClient(
        transport=ASGITransport(app=crash_app, raise_app_exceptions=False),
        base_url="http://test",
    ) as client:
        response = await client.get("/boom", headers={REQUEST_ID_HEADER: "req_log_42"})

    # The unique fingerprint must appear in the captured logs, with the
    # request id present for correlation.
    assert "traceback-fingerprint-abc123" in caplog.text
    assert "req_log_42" in caplog.text
    assert response.status_code == 500


# ---------------------------------------------------------------------------
# Real app regression — already-wired production app must also be sanitized
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_production_app_emits_request_id_header() -> None:
    """The real production app must register the request id on every
    response, including the OpenAPI schema endpoint used by SDK tooling."""

    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as client:
        response = await client.get("/openapi.json")

    assert response.status_code == 200
    rid = response.headers[REQUEST_ID_HEADER]
    assert rid.startswith("req_")


def test_production_app_supplies_stable_cookie_policy_error_code() -> None:
    """The auth_setup.py refresh endpoint must return a fixed error code
    instead of ``str(e)``. We can't easily trigger the actual cookie policy
    failure, so we visit the source and assert the literal token is
    present, and that the ``detail=str(e)`` pattern is gone."""

    auth_source = (ROOT / "orchestrator" / "routes" / "auth_setup.py").read_text()
    # The literal fix token must be present in both the setup and refresh
    # endpoints.
    assert auth_source.count("cookie_policy_invalid") >= 2
    # The leaky pattern must be gone from auth_setup.py.
    assert "detail=str(e)" not in auth_source


def test_production_app_omits_str_e_in_main_chat_completion() -> None:
    """The OpenAI-compatible chat completion endpoint must not leak
    ``str(e)`` in its 500 response."""

    main_source = (ROOT / "orchestrator" / "main.py").read_text()
    # The fix replaces the leaky `raise HTTPException(status_code=500,
    # detail=str(e))` pattern with `detail=_GENERIC_INTERNAL_ERROR`.
    # Check that the leaky pattern is gone (allowing other valid instances
    # elsewhere — but the specific chat-completion path is replaced).
    # We anchor on the chat completion route which is the one we changed.
    assert "OpenAI-compatible chat completion failed" in main_source


def test_main_py_no_new_detail_str_e_in_runtime_error_branches() -> None:
    """Static gate: the runtime-error path in ``/v1/chat/completions`` must
    not go back to leaking ``str(e)``. We accept the auth_setup path for
    the historical reason (well-scoped cookie policy errors are now a
    fixed token)."""

    main_source = (ROOT / "orchestrator" / "main.py").read_text()
    # The chat completion route's exception branch must use the generic
    # message constant, not ``str(e)``. The branch logging message is
    # the unique anchor — the comment block above only appears in this
    # route's exception handler.
    match = re.search(
        r"OpenAI-compatible chat completion failed.*?raise HTTPException\(\s*status_code=500,\s*detail=([^\n)]+)\)",
        main_source,
        flags=re.DOTALL,
    )
    assert match is not None, "Could not find the chat completion exception handler in main.py"
    detail_value = match.group(1).strip()
    assert detail_value == "_GENERIC_INTERNAL_ERROR", (
        f"Expected detail=_GENERIC_INTERNAL_ERROR, got {detail_value!r}"
    )
    assert "str(e)" not in match.group(0)


# ---------------------------------------------------------------------------
# Round-1 (PR #218): additional regressions for the 5 Codex findings on
# head fb5202f4 (review posted 2026-08-10T20:14Z).
# ---------------------------------------------------------------------------


def test_streaming_chat_branches_do_not_leak_str_e() -> None:
    """Round-1 finding: streaming error branches in ``orchestrator/main.py``
    (OpenAI-compatible chat at line 1302 and native ``/chat`` at line
    2176) and ``orchestrator/daemon.py`` ``stream_sse_chat`` (line 795)
    used to emit ``str(e)`` to the client on the SSE error payload.
    Static gate: no ``f\"...{str(e)}\"`` literal in any of those branches.
    """

    main_source = (ROOT / "orchestrator" / "main.py").read_text()
    daemon_source = (ROOT / "orchestrator" / "daemon.py").read_text()

    # The streaming chat completion branch and the native /chat SSE
    # error branch both used to contain `f"... {str(e)}"`. After the
    # round-1 fix, they call _sse_error_message(...) which never takes
    # the exception.
    assert 'delta=OpenAIDeltaMessage(content=f"Error: {str(e)}")' not in main_source
    assert '"message": str(e),' not in main_source
    assert 'make_envelope("error", {"message": str(e)}' not in daemon_source
    assert "terminal_reason = str(e)" not in daemon_source


def test_cookie_policy_invalid_appears_in_all_four_endpoints() -> None:
    """Round-1 finding: two ``detail=str(exc)`` callsites in
    ``orchestrator/routes/auth_setup.py`` (lines 616 and 1067) leaked
    ``daemon_cookie_secure=false is not allowed in production``. After
    the fix, all four cookie-policy failure callsites use the stable
    ``cookie_policy_invalid`` token.
    """

    auth_source = (ROOT / "orchestrator" / "routes" / "auth_setup.py").read_text()
    assert auth_source.count("cookie_policy_invalid") >= 4, (
        "Expected cookie_policy_invalid in all 4 cookie-policy failure "
        "callsites (setup, refresh, /v1/auth/email/complete, "
        "/v1/auth/google/complete); found "
        f"{auth_source.count('cookie_policy_invalid')} occurrences."
    )
    # No detail=str(e) or detail=str(exc) leaks anywhere in auth_setup.
    assert "detail=str(e)" not in auth_source
    assert "detail=str(exc)" not in auth_source


def test_request_id_is_always_server_generated() -> None:
    """Round-1 finding: the inbound ``X-Request-ID`` was reused as the
    sole correlation handle, allowing an attacker to pre-stage a known
    id and pollute log searches. After the fix, every request gets a
    server-generated ``req_`` prefix regardless of the inbound header.
    """

    request_id_module = (ROOT / "orchestrator" / "request_id.py").read_text()
    # The fix introduced _resolve_request_id returning a tuple
    # (server_id, inbound_id); the server id is always from _new_request_id().
    assert "_new_request_id()" in request_id_module
    assert "return sanitized or _new_request_id()" not in request_id_module, (
        "Inbound X-Request-ID must not be reused as the correlation handle"
    )


def test_inbound_request_id_is_preserved_separately() -> None:
    """Round-1 finding: with the new design, an inbound ``X-Request-ID``
    must be surfaced as ``X-Client-Request-ID`` on the response so the
    upstream proxy / load-test harness still has its correlation handle.
    """

    request_id_module = (ROOT / "orchestrator" / "request_id.py").read_text()
    assert "CLIENT_REQUEST_ID_HEADER" in request_id_module
    assert "X-Client-Request-ID" in request_id_module
    assert "get_client_request_id" in request_id_module


def test_cors_exposes_request_id_header() -> None:
    """Round-1 finding: the CORS configuration did not expose
    ``X-Request-ID``, so browser code at an allowed origin could not
    read the correlation handle on cross-origin responses.
    """

    main_source = (ROOT / "orchestrator" / "main.py").read_text()
    assert "CORS_EXPOSE_HEADERS" in main_source
    assert "expose_headers=list(CORS_EXPOSE_HEADERS)" in main_source
    assert "X-Request-ID" in main_source


def test_outer_cors_middleware_is_wired() -> None:
    """Round-1 finding: an unhandled 500 path bypasses the inner
    ``CORSMiddleware`` (Starlette's ``ServerErrorMiddleware`` is
    outermost), so browser code at an allowed origin cannot read the
    sanitized body. The fix wraps the built stack with a new
    ``_OuterCORSMiddleware`` that mirrors the CORS response headers
    onto the unhandled-500 response.
    """

    main_source = (ROOT / "orchestrator" / "main.py").read_text()
    assert "_OuterCORSMiddleware(" in main_source
    request_id_module = (ROOT / "orchestrator" / "request_id.py").read_text()
    assert "class _OuterCORSMiddleware" in request_id_module


def test_handled_error_logs_include_request_id() -> None:
    """Round-1 finding: handled-error log entries (cookie policy and
    OpenAI-compatible chat completion) omitted the request id so
    support could not correlate the sanitized response with the
    server-side traceback.
    """

    auth_source = (ROOT / "orchestrator" / "routes" / "auth_setup.py").read_text()
    main_source = (ROOT / "orchestrator" / "main.py").read_text()

    # All four cookie policy log entries carry request_id.
    assert auth_source.count("request_id=%s") >= 4
    # The OpenAI-compatible chat completion log entry carries request_id.
    chat_match = re.search(
        r"OpenAI-compatible chat completion failed.*?raise HTTPException\(\s*status_code=500",
        main_source,
        flags=re.DOTALL,
    )
    assert chat_match is not None
    assert "request_id=%s" in chat_match.group(0)


def test_outer_cors_middleware_merges_vary_origin() -> None:
    """Round-2 finding: when the outer middleware reflects the request
    ``Origin`` into ``Access-Control-Allow-Origin``, the response must
    carry ``Vary: Origin`` so intermediaries don't cache the response
    and replay it for a different origin. The merge must be idempotent
    and preserve any pre-existing ``Vary`` values.
    """

    from starlette.datastructures import MutableHeaders

    from orchestrator.request_id import _merge_vary_origin

    # No existing Vary header → adds one with Origin.
    headers = MutableHeaders()
    _merge_vary_origin(headers)
    assert headers.get("Vary") == "Origin"

    # Existing Vary with a different field → merges.
    headers = MutableHeaders()
    headers["Vary"] = "Accept-Encoding"
    _merge_vary_origin(headers)
    assert (headers.get("Vary") or "").lower() == "accept-encoding, origin"

    # Already contains Origin (case-insensitive) → no duplicate.
    headers = MutableHeaders()
    headers["Vary"] = "origin, Accept-Encoding"
    _merge_vary_origin(headers)
    vary = headers.get("Vary") or ""
    assert vary.lower().count("origin") == 1


def test_outer_cors_middleware_calls_merge_vary_origin() -> None:
    """Static check: ``_OuterCORSMiddleware`` calls the Vary-Origin
    merge helper so the response cannot be cached cross-origin
    (round-2 finding on PR #219).
    """

    request_id_source = (ROOT / "orchestrator" / "request_id.py").read_text()
    assert "_merge_vary_origin" in request_id_source
    assert "def _merge_vary_origin" in request_id_source
    # The merge must be wired into the outer CORS send wrapper.
    outer_block = re.search(
        r"class _OuterCORSMiddleware.*?async def send_with_outer_cors.*?await send\(message\)",
        request_id_source,
        flags=re.DOTALL,
    )
    assert outer_block is not None
    assert "_merge_vary_origin(headers)" in outer_block.group(0)


def test_email_and_google_complete_rate_limit_runs_before_cookie_policy() -> None:
    """Round-2 finding: ``logger.exception`` on a CookiePolicyError was
    reachable BEFORE the IP rate limit fired, allowing an unauthenticated
    caller to generate unbounded full tracebacks. The IP rate limit
    must now run before cookie-policy validation in both
    ``/v1/auth/email/complete`` and ``/v1/auth/google/complete``.
    """

    auth_source = (ROOT / "orchestrator" / "routes" / "auth_setup.py").read_text()

    cases = [
        # (function name, rate-limit call to look for, cookie-config call to look for)
        (
            "email_complete_endpoint",
            "_email_complete_ip_rate_limit_policies",
            "make_refresh_cookie_config(",
        ),
        (
            "google_complete_endpoint",
            "_google_complete_rate_limit_policies",
            "make_refresh_cookie_config(",
        ),
    ]
    for fn_name, rl_marker, cookie_marker in cases:
        # Slice the function body from its ``async def`` to the next
        # ``async def`` (or end of file).
        fn_pattern = re.compile(
            rf"async def {fn_name}\(.*?(?=^async def |\Z)",
            flags=re.DOTALL | re.MULTILINE,
        )
        fn_match = fn_pattern.search(auth_source)
        assert fn_match is not None, f"{fn_name} body not found"
        body = fn_match.group(0)
        # The IP rate-limit call must come BEFORE the cookie-policy
        # validation block (which is the call to
        # ``make_refresh_cookie_config``).
        rl_idx = body.find(rl_marker)
        cookie_idx = body.find(cookie_marker)
        assert rl_idx >= 0, f"rate-limit marker {rl_marker!r} not found in {fn_name}"
        assert cookie_idx >= 0, f"cookie marker {cookie_marker!r} not found in {fn_name}"
        assert rl_idx < cookie_idx, (
            f"in {fn_name}, rate limit (idx {rl_idx}) must run BEFORE "
            f"cookie policy validation (idx {cookie_idx})"
        )


def test_enroll_complete_log_labels_event_as_enrollment_failure() -> None:
    """Round-2 finding: the cookie-policy log entry inside
    ``enroll_complete_endpoint`` previously said "during refresh",
    sending operators searching by endpoint toward the wrong flow.
    The log message must identify the enrollment endpoint.
    """

    auth_source = (ROOT / "orchestrator" / "routes" / "auth_setup.py").read_text()
    enroll_match = re.search(
        r"async def enroll_complete_endpoint\(.*?^async def ",
        auth_source,
        flags=re.DOTALL | re.MULTILINE,
    )
    assert enroll_match is not None
    body = enroll_match.group(0)
    # The fixed log message must be present in the enroll endpoint.
    assert "during /v1/auth/enroll/complete" in body
    # The old "during refresh" wording must NOT be present in the
    # enroll endpoint (it would mislead operators searching the
    # /v1/auth/refresh log channel).
    assert "Cookie policy validation failed during refresh" not in body


def test_native_chat_reuses_http_correlation_id() -> None:
    """Round-2 finding: the native ``/chat`` SSE error envelope and
    streaming-error log previously used a route-local id created by
    ``new_request_id()`` at the top of the handler, while the new
    request-id middleware independently generated the exposed
    ``X-Request-ID`` response header. The result was that a browser
    reporting the header value gave support an id that did not appear
    in the traceback log or SSE error message. The fix initializes the
    route-local id from ``get_request_id(request)`` so the advertised
    correlation handle is consistent end-to-end.
    """

    main_source = (ROOT / "orchestrator" / "main.py").read_text()
    chat_match = re.search(
        r"^async def chat\([\s\S]*?\)\s*->\s*StreamingResponse:",
        main_source,
        flags=re.MULTILINE,
    )
    assert chat_match is not None, "chat() body not found"
    end = main_source.find("\nasync def ", chat_match.end())
    if end == -1:
        end = len(main_source)
    body = main_source[chat_match.start() : end]
    # The first assignment to ``request_id`` inside chat() must read the
    # middleware-attached value rather than mint a fresh one.
    first_assign = re.search(r"request_id\s*=\s*[^\n]+", body)
    assert first_assign is not None
    assert "get_request_id(request)" in first_assign.group(0), (
        "chat() must initialize its SSE error correlation id from "
        "get_request_id(request) so the SSE error envelope, streaming "
        "log, and X-Request-ID response header all advertise the same "
        "handle. Got: " + first_assign.group(0)
    )


def test_outer_cors_middleware_handles_wildcard_origins() -> None:
    """Round-2 finding: when the operator configured
    ``DAEMON_ALLOWED_ORIGINS=*``, the outer middleware's literal
    ``request_origin in self._allowed`` check never matched, disabling
    CORS headers on every unhandled 500. The fix treats ``"*"`` as a
    wildcard that echoes the request origin, mirroring the inner
    middleware's permissive semantics for that single configuration.
    """

    from orchestrator.request_id import _OuterCORSMiddleware

    async def _no_op_app(scope, receive, send):  # pragma: no cover - never invoked
        return None

    middleware = _OuterCORSMiddleware(_no_op_app, allowed_origins=("*",))
    assert getattr(middleware, "_allow_all", False) is True
