"""Request ID middleware.

Every HTTP request gets a stable identifier that is propagated to the
response header and through structured logs. Inbound requests may supply
their own ``X-Request-ID`` (e.g. an upstream proxy or load-test harness);
otherwise we generate a fresh UUID4 prefixed with ``req_``.

The identifier is also attached to the request state so route handlers
and the global exception handler can include it in error responses and
log lines without re-reading the header.
"""

from __future__ import annotations

import re
import secrets

from starlette.datastructures import MutableHeaders
from starlette.requests import Request
from starlette.types import ASGIApp, Message, Receive, Scope, Send

REQUEST_ID_HEADER = "X-Request-ID"
_STATE_REQUEST_ID = "request_id"

# Bound to a reasonable printable length so a malicious inbound value
# cannot be reflected into a log file or response header with unbounded
# size. 128 is plenty for a UUID4 hex + any operator prefix.
_MAX_INBOUND_LEN = 128
# Acceptable inbound characters: ASCII alphanumerics, dash, underscore,
# dot, slash, colon, plus. Anything else is replaced with ``_``.
_INBOUND_RE = re.compile(r"[^A-Za-z0-9._/:+\-]")


def _sanitize_inbound(value: str) -> str | None:
    """Sanitize a client-supplied request id.

    Returns ``None`` when the value is empty or contains only
    non-allowed characters. Truncated to :data:`_MAX_INBOUND_LEN` chars.
    """

    if not value:
        return None
    if len(value) > _MAX_INBOUND_LEN:
        value = value[:_MAX_INBOUND_LEN]
    cleaned = _INBOUND_RE.sub("_", value)
    return cleaned or None


def _new_request_id() -> str:
    return f"req_{secrets.token_urlsafe(16)}"


def _resolve_request_id(scope: Scope) -> str:
    """Pick the request id for this scope: client's if valid, else new."""

    headers = MutableHeaders(scope=scope)
    inbound = headers.get(REQUEST_ID_HEADER)
    sanitized = _sanitize_inbound(inbound) if inbound else None
    return sanitized or _new_request_id()


def _has_header(headers: MutableHeaders, name: str) -> bool:
    lowered = name.lower()
    return any(k.lower() == lowered for k in headers.keys())


class RequestIdMiddleware:
    """Add an X-Request-ID header to every response.

    Inbound requests may set ``X-Request-ID``; the value is sanitized
    and reused. Otherwise a fresh ``req_<urlsafe>`` id is generated.
    The id is also attached to ``request.scope["state"]`` so handlers
    and exception handlers can read it without re-parsing the header.
    """

    def __init__(self, app: ASGIApp) -> None:
        self.app = app

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] != "http":
            await self.app(scope, receive, send)
            return

        request_id = _resolve_request_id(scope)
        scope.setdefault("state", {})[_STATE_REQUEST_ID] = request_id

        async def send_with_request_id(message: Message) -> None:
            if message["type"] == "http.response.start":
                headers = MutableHeaders(scope=message)
                if not _has_header(headers, REQUEST_ID_HEADER):
                    headers[REQUEST_ID_HEADER] = request_id
            await send(message)

        await self.app(scope, receive, send_with_request_id)


class _OuterRequestIdMiddleware:
    """Wraps the FastAPI ASGI stack so 500 responses generated by
    Starlette's outermost ``ServerErrorMiddleware`` also carry the
    request id.

    ``add_middleware`` only places middleware inside
    ``ServerErrorMiddleware``, so unhandled exceptions bypass the inner
    ``RequestIdMiddleware``. This outer wrap mirrors the same value into
    the response header for 500s.
    """

    def __init__(self, app: ASGIApp) -> None:
        self.app = app

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] != "http":
            await self.app(scope, receive, send)
            return

        request_id = _resolve_request_id(scope)
        scope.setdefault("state", {})[_STATE_REQUEST_ID] = request_id

        async def send_with_outer_request_id(message: Message) -> None:
            if message["type"] == "http.response.start":
                headers = MutableHeaders(scope=message)
                if not _has_header(headers, REQUEST_ID_HEADER):
                    headers[REQUEST_ID_HEADER] = request_id
            await send(message)

        await self.app(scope, receive, send_with_outer_request_id)


def get_request_id(request: Request) -> str | None:
    """Read the request id attached to ``request.scope``.

    Returns ``None`` if the middleware has not run (e.g. the request was
    handled outside of the ASGI stack).
    """

    state = request.scope.get("state") or {}
    rid = state.get(_STATE_REQUEST_ID)
    return rid if isinstance(rid, str) and rid else None
