"""Identity services for hosted identity routes.

Reusable primitives that back the hosted identity endpoints
(/v1/auth/email/*, /v1/auth/google/*, /v1/auth/setup,
/v1/auth/enroll/*, /v1/auth/refresh). The rate limiter (TODO 7),
the account/tenant/invite/provider service (TODO 8), the
identity-aware device-session issuance helper (TODO 9), the
email-challenge service (TODO 10), the mail-sender
abstraction (TODO 10), the Google ID-token verification
service (TODO 12), and the new-device notification helper
(TODO 14) are the services implemented today. The
TODO 9 / TODO 12 helpers are backend-only boundaries — no HTTP
routes are added at those TODOs because identity session
issuance MUST be gated on a verified identity proof (email
code consumption or Google ID-token verification), and those
routes are TODO 11 and TODO 13. TODO 14 adds the post-issue
new-device email notification that the TODO 11 and TODO 13
routes schedule as a FastAPI `BackgroundTasks` coroutine
after a successful `issue_device_session`.
"""

from __future__ import annotations

from orchestrator.services.identity.rate_limiter import (
    RateLimitDecision,
    RateLimiter,
    RateLimitPolicy,
    RateLimitUnavailableError,
    hash_key_material,
)
from orchestrator.services.identity.rate_limit_dep import (
    ScopeKind,
    client_ip_for_key,
    enforce_rate_limit,
    get_chat_rate_limit_metrics,
    get_rate_limiter,
    record_chat_rate_limit_rejection,
    record_chat_rate_limit_request,
)
from orchestrator.services.identity.account_service import (
    AccountService,
    AccountServiceError,
    ClaimResult,
    EmailNotVerified,
    InviteInvalidOrExpired,
    InviteOnlyRejection,
    ProviderCollision,
    ProviderLink,
    SignupDisabled,
    SupportsIdentityQueries,
    TenantRow,
    UserRow,
    normalize_email,
)
from orchestrator.services.identity.session_issuance import (
    DEFAULT_PRIVATE_REFRESH_TTL_DAYS,
    DEFAULT_TEMPORARY_REFRESH_TTL_SECONDS,
    DevicePersistence,
    InvalidClientKind,
    InvalidDevicePersistence,
    IssueSessionRequest,
    IssuedSession,
    SessionIssuanceError,
    SessionRefreshTransport,
    SupportsSessionIssuanceQueries,
    TEMPORARY_DB_FALLBACK_TTL_SECONDS,
    issue_device_session,
)
from orchestrator.services.identity.email_challenge import (
    EMAIL_CODE_NUM_DIGITS,
    DEFAULT_MAX_ATTEMPTS,
    DEFAULT_TTL_SECONDS,
    DevSink,
    EmailChallengeConsumeRequest,
    EmailChallengeInvalid,
    EmailChallengeIssueRequest,
    EmailChallengeLocked,
    EmailChallengeRow,
    EmailChallengeService,
    EmailChallengeServiceError,
    EmailChallengeUnavailable,
    SupportsEmailChallengeQueries,
    compute_code_verifier,
    generate_email_code,
    hash_ip_for_storage,
    hash_user_agent_for_storage,
    normalize_code,
)
from orchestrator.services.identity.mail_sender import (
    ConsoleMailSender,
    DisabledMailSender,
    MailMessage,
    MailSendError,
    MailSendResult,
    MailSender,
    MailSenderConfigError,
    MailSenderError,
    SmtpMailSender,
    get_mail_sender,
)
from orchestrator.services.identity.device_notification import (
    NOTIFICATION_SUBJECT,
    REVOKE_GUIDANCE,
    DeviceNotification,
    render_device_notification,
    schedule_device_notification,
    send_device_notification,
)
from orchestrator.services.identity.google_verifier import (
    DEFAULT_TTL_SECONDS as GOOGLE_DEFAULT_TTL_SECONDS,
    GOOGLE_ISSUER_CANONICAL,
    GOOGLE_ISSUER_LEGACY,
    GoogleIdTokenVerifier,
    GoogleIdTokenVerifyRequest,
    GoogleNonceConsumeRequest,
    GoogleNonceInvalid,
    GoogleNonceIssueRequest,
    GoogleNonceRow,
    GoogleVerifierError,
    GoogleVerifierService,
    GoogleVerifierUnavailable,
    GoogleTokenInvalid,
    MAX_TOKEN_AGE_SECONDS,
    NONCE_NUM_BYTES,
    SupportsGoogleNonceQueries,
    VerifiedGoogleIdentity,
    audience_allowed,
    compute_nonce_verifier,
    default_google_id_token_verifier,
    generate_google_nonce,
    hash_ip_for_storage as hash_ip_for_storage_google,
    hash_user_agent_for_storage as hash_user_agent_for_storage_google,
    issuer_allowed,
    parse_audience_allowlist,
)

__all__ = [
    "GOOGLE_DEFAULT_TTL_SECONDS",
    "GOOGLE_ISSUER_CANONICAL",
    "GOOGLE_ISSUER_LEGACY",
    "MAX_TOKEN_AGE_SECONDS",
    "NONCE_NUM_BYTES",
    "AccountService",
    "AccountServiceError",
    "ClaimResult",
    "ConsoleMailSender",
    "DEFAULT_MAX_ATTEMPTS",
    "DEFAULT_PRIVATE_REFRESH_TTL_DAYS",
    "DEFAULT_TEMPORARY_REFRESH_TTL_SECONDS",
    "DEFAULT_TTL_SECONDS",
    "DevSink",
    "DeviceNotification",
    "DevicePersistence",
    "DisabledMailSender",
    "EMAIL_CODE_NUM_DIGITS",
    "EmailChallengeConsumeRequest",
    "EmailChallengeInvalid",
    "EmailChallengeIssueRequest",
    "EmailChallengeLocked",
    "EmailChallengeRow",
    "EmailChallengeService",
    "EmailChallengeServiceError",
    "EmailChallengeUnavailable",
    "EmailNotVerified",
    "GoogleIdTokenVerifier",
    "GoogleIdTokenVerifyRequest",
    "GoogleNonceConsumeRequest",
    "GoogleNonceInvalid",
    "GoogleNonceIssueRequest",
    "GoogleNonceRow",
    "GoogleTokenInvalid",
    "GoogleVerifierError",
    "GoogleVerifierService",
    "GoogleVerifierUnavailable",
    "InvalidClientKind",
    "InvalidDevicePersistence",
    "InviteInvalidOrExpired",
    "InviteOnlyRejection",
    "IssueSessionRequest",
    "IssuedSession",
    "MailMessage",
    "MailSendError",
    "MailSendResult",
    "MailSender",
    "MailSenderConfigError",
    "MailSenderError",
    "NOTIFICATION_SUBJECT",
    "REVOKE_GUIDANCE",
    "ProviderCollision",
    "ProviderLink",
    "RateLimitDecision",
    "RateLimitPolicy",
    "RateLimiter",
    "RateLimitUnavailableError",
    "ScopeKind",
    "SessionIssuanceError",
    "SessionRefreshTransport",
    "SignupDisabled",
    "SmtpMailSender",
    "SupportsEmailChallengeQueries",
    "SupportsGoogleNonceQueries",
    "SupportsIdentityQueries",
    "SupportsSessionIssuanceQueries",
    "TEMPORARY_DB_FALLBACK_TTL_SECONDS",
    "TenantRow",
    "UserRow",
    "VerifiedGoogleIdentity",
    "audience_allowed",
    "client_ip_for_key",
    "compute_code_verifier",
    "compute_nonce_verifier",
    "default_google_id_token_verifier",
    "enforce_rate_limit",
    "generate_email_code",
    "generate_google_nonce",
    "get_chat_rate_limit_metrics",
    "get_mail_sender",
    "get_rate_limiter",
    "hash_ip_for_storage",
    "hash_ip_for_storage_google",
    "hash_key_material",
    "hash_user_agent_for_storage",
    "hash_user_agent_for_storage_google",
    "issuer_allowed",
    "issue_device_session",
    "normalize_code",
    "normalize_email",
    "parse_audience_allowlist",
    "record_chat_rate_limit_rejection",
    "record_chat_rate_limit_request",
    "render_device_notification",
    "schedule_device_notification",
    "send_device_notification",
]
