import DOMPurify, { type Config } from "dompurify";

const sanitizeConfig: Config = {
  ALLOWED_TAGS: [
    "html",
    "head",
    "body",
    "div",
    "span",
    "p",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "script",
    "style",
    "input",
    "button",
    "label",
    "form",
    "canvas",
    "svg",
    "path",
    "rect",
    "circle",
    "text",
    "table",
    "tr",
    "td",
    "th",
    "thead",
    "tbody",
    "ul",
    "ol",
    "li",
    "a",
    "br",
    "hr",
    "pre",
    "code",
    "strong",
    "em",
    "b",
    "i",
    "u",
    "small",
    "mark",
  ],
  ALLOWED_ATTR: [
    "class",
    "id",
    "style",
    "type",
    "value",
    "placeholder",
    "onclick",
    "for",
    "href",
    "src",
    "alt",
    "title",
    "width",
    "height",
    "viewBox",
    "d",
    "cx",
    "cy",
    "r",
    "fill",
    "stroke",
    "stroke-width",
  ],
  ALLOW_DATA_ATTR: false,
  FORBID_ATTR: [
    "onload",
    "onerror",
    "onmouseover",
    "onfocus",
    "onblur",
    "onchange",
    "onsubmit",
    "onkeydown",
    "onkeyup",
    "onkeypress",
    "oncontextmenu",
    "ondrag",
    "ondrop",
  ],
  FORBID_TAGS: ["iframe", "frame", "object", "embed", "link", "meta", "base", "formaction", "formmethod"],
};

export function sanitizeHtml(html: string): string {
  return DOMPurify.sanitize(html, sanitizeConfig);
}

export type { Config as SanitizeConfig } from "dompurify";